### PR TITLE
 [STRAT-138] Generate test elevation output from ASC2021 data

### PR DESCRIPTION
**Pull request by minkim0320**
+ Ticket was to test routemodel for elevations using sample ASC data from 2021
+ We developed a python script to build the points, call the API and store 1000 elevations outputs in CSV file (using polyline method)
+ Please check the output csv file in routemodel/routes/ASC2021/test_elevation_output.csv 
+ CSV output only contains the index and elevation data since it was made using polyline method from 25 sample points.
+ We weren't sure  whether to put the python script as well, if we don't need it, we can delete it. For reference, it is located in routemodel/tests/generate_test_elevation_output.py

### CODE REVIEW

**Review by e-wai — CHANGES_REQUESTED** [review]
This looks good! can we add in the latitude and longitude as headers in the csv file so we can later graph the route with distance travelled vs elevations? (also, your script is lovely, but I don't think we need it in the repository)

**Comment by klinhdo** [comment]
We added travel distance to the CSV file. 
The travel distance is generated by
- Call Route API using 25 data points from ASC2021_elevations_draft.csv (remove the 24th point due to parameter limit). 
- For each elevation data, take the total distance from the above response, divided by 999 then multiply it by the row number to get the distance.

**Comment by minkim0320** [comment]
This PR is ready for complete review
+ we verified that the total distance calculations are correct based on the ASC2021 sample points
+ Please check the output csv file in routemodel/routes/ASC2021/test_elevation_output.csv

**Comment by ufshk** [comment]
CSV looks good.

I know @e-wai has said no need for the script, I personally think it would be fine to have but I'll let her decide. Do keep it with you guys for now, we may have somewhere to keep it later.

**Review by ufshk — APPROVED** [review]
Approved.

**Review by e-wai — APPROVED** [review]
Looks fantastic, thank you both! Out of curiosity, have you tried graphing it?

**Comment by klinhdo** [comment]
Here is the graph of the distance travelled:
ASC2021_distance_travelled

**Pull request merged**
