### PR TITLE
ONBOARDING - Rodrigo

### PR DESCRIPTION
**Pull request by rodrigotiscareno**
Added message "Rodrigo says hello" at the bottom of README.md file.

### CODE REVIEW

**Review by ufshk — COMMENTED** [review]
The onboarding part seems good, I'm just confused as to why git is saying you've changed all these other files. Won't block the PR, but it may be good to try to make it so only your changes in the README file are recognized.

**Comment by e-wai** [comment]
@ufshk I created `onboarding-hello` before those two other PRs were merged, I think. So @rodrigotiscareno has those commits updated on his fork, but they don't exist on `onboarding-hello` branch, and so they appear as added commits. Shouldn't a problem normally? (And if it is, a rebase should solve that)

@rodrigotiscareno this looks all good to me! Congrats 🥳

**Comment by e-wai** [comment]
This looks done to me -> unless @rodrigotiscareno has any objections, I'll close it?

**Comment by rodrigotiscareno** [comment]
Yup! Good to close now, thank you.

**Pull request closed without merging**
