### PR TITLE
[STRAT-136] Generate speedlimits given ASC2021 data

### PR DESCRIPTION
**Pull request by chriistine**

### CODE REVIEW

**Review by e-wai — COMMENTED** [review]
I'm not sure we actually need `generate_test_speedlimits.py` in the repository, but it looks good. Did you figure out why there's speed limits of 0kph? Can we also try doing a request with more points (ie., use polyline method in `routes.py` to get more points, and then send them to the speedlimits API for a more granular picture of what the speedlimits are through the route?)

**Comment by chriistine** [comment]
We have updated the output file and it is now ready for review:
- We used routes.py to request more points to generate the speedlimits
- The output is in routemodel/routes/ASC2021/generated_test_speedlimits.csv
- Despite generating more points, we continue to get 0 kph for some of the pts. We suspect that it has to do with the API response itself.

**Review by ufshk — COMMENTED** [review]
File seems good... have you searched online about some of the streets that don't have speedlimits here? Or searched if maybe Bing Maps has some of these limits missing by any chance? If so, comment again and let me know, I'll approve the PR then.

**Comment by e-wai** [comment]
Yup, similar comment to Umar. Can we try entering some of the 0kph points into Google/Bing Maps and checking if they're on actual roads

**Comment by e-wai** [comment]
Future work TODO -> why are we getting so many 0kph?
- not on a road -> 0kph; some on a road -> still 0kph
- do we need a distinct snap to road call?
- mph -> kph is causing the weird values

**Review by e-wai — APPROVED** [review]
Future work TODO -> why are we getting so many 0kph?

- not on a road -> 0kph; some on a road -> still 0kph
- do we need a distinct snap to road call?
- mph -> kph is causing the weird values

(Still merging)

**Pull request merged**
