### PR TITLE
Another initial fit of HI and LO coils

### PR DESCRIPTION
**Pull request by KristinChengWu**
Built on @e-wai fit on the HI/LO coil data #78 

This graphs the efficiency based on purely torque and speed. 

Since we won't know current or voltage, its relationship with speed and torque is predicted using the provided data. Thus we can calculate efficiency based on only torque and speed values. 

The calculated datapoints don't always match up with the true efficiency, so there are some tweaks that need to be made there... 

LOGraph
HIGraph

### CODE REVIEW

**Review by e-wai — APPROVED** [review]

**Comment by ufshk** [comment]
@KristinChengWu go ahead and merge this! I would do it myself but I didn't even review so...

**Comment by KristinChengWu** [comment]
@e-wai uh I don't think I have write access to merge pull requests

**Comment by KristinChengWu** [comment]
> @e-wai uh I don't think I have write access to merge pull requests

oh wait nvm it was @ufshk that messaged

**Comment by ufshk** [comment]
It was me... I am unsure of why Emma hasn't merged it, so I deleted that comment. I'll ask Shio/Emma about it.

**Comment by e-wai** [comment]
Waiting to see if Micah Black has a chance to take a look first

**Comment by e-wai** [comment]
Merging but it's imperfect (see outliers and concavity in HI coil graph)

**Pull request merged**
