### PR TITLE
[STRAT-90] Reject negative velocity

### PR DESCRIPTION
**Pull request by KristinChengWu**
Here I asserted all velocity inputs to be non-negative except for vwind (which I'm assuming can be negative if it's against the car). Let me know if this is okay!

### CODE REVIEW

**Comment by e-wai** [comment]
Sorry, this was a ticket thing. Can we just ignore the value when it's negative, rather than throwing an error.

**Comment by KristinChengWu** [comment]
Not sure what you mean by ignore. So if it's negative velocity, turn it into positive? Or return? Or keep the default value? If the last case, some functions don't have default values for velocity.

**Comment by e-wai** [comment]
So I think the only change we actually need is that if they pass speed_min as a 0 or negative value, default to 15 (or whatever the default value is). And this wasn't on the ticket, but can we also check that speed_max > speed_min, and if not, set speed_max = speed_min?

**Comment by KristinChengWu** [comment]
If `speed_min_ms` is passed 0 and is changed to the default value, it messes up with some of the tests, specifically `test_calculate_SOC_values_nonzero_values` and `test_calculate_SOC_values_initial_soc_non_1` since in each case `min_speed` is set as 0 

So I think it makes sense if the speed is changed to the default only if speed_min_ms < 0, not speed_min_ms <= 0. I'll create a new pull request.

**Pull request closed without merging**
